
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

  servlet:
    multipart:
      max-file-size: 50MB #设置上传文件的最大大小，默认为 1MB
      max-request-size: 50MB #设置请求中最大允许的文件大小，默认为 10MB

# 解决这个错误：org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper';
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: ${spring.redis.host}
    port: ${spring.redis.port}
    password: ${spring.redis.password}
    pool:
      max-active: 100
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8
      min-idle: 0
    timeout: 1200

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

minio:
  url: http://127.0.0.1:9001
  username: admin
  password: 12345678
  bucketName: anyim
  image:
    max-limit: 10 #单位M
    thumb-size: 51200  #单位B
  file:
    max-limit: 200 #单位M
  ttl: 365 #单位天

#自定义配置
custom:
  snow-flake:
    worker-datacenter-config: ${worker-datacenter-config}