
spring:
  redis:
    host: ${spring.redis.host}
    port: ${spring.redis.port}
    password: ${spring.redis.password}
    pool:
      max-active: 100
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 1200


websocket:
  port: 8100
  path: /ws
  log-level: DEBUG  # LoggingHandler的日志级别
  topic-distribute: ${websocket.topic-distribute}