server:
  port: 8000

spring:
  application:
    name: anyim-netty
  profiles:
    active: dev

  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        import-check:
          enabled: false
      discovery:
        server-addr: localhost:8848


  redis:
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 100
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 1200


websocket:
  port: 8100
  path: /ws

jwt:
  accessToken:
    expire: 1800 #半个小时
    secret: HZHDhdfjdfj
  refreshToken:
    expire: 3600 #1小时
    secret: GHBsfh2sags