// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

// Protobuf Java Version: 4.26.1
package com.hibob.anyim.netty.protobuf;

public interface BodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hibob.anyim.netty.protobuf.Body)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fromId = 1;</code>
   * @return The fromId.
   */
  java.lang.String getFromId();
  /**
   * <code>string fromId = 1;</code>
   * @return The bytes for fromId.
   */
  com.google.protobuf.ByteString
      getFromIdBytes();

  /**
   * <code>string fromClient = 2;</code>
   * @return The fromClient.
   */
  java.lang.String getFromClient();
  /**
   * <code>string fromClient = 2;</code>
   * @return The bytes for fromClient.
   */
  com.google.protobuf.ByteString
      getFromClientBytes();

  /**
   * <code>optional string toId = 3;</code>
   * @return Whether the toId field is set.
   */
  boolean hasToId();
  /**
   * <code>optional string toId = 3;</code>
   * @return The toId.
   */
  java.lang.String getToId();
  /**
   * <code>optional string toId = 3;</code>
   * @return The bytes for toId.
   */
  com.google.protobuf.ByteString
      getToIdBytes();

  /**
   * <code>optional string toClient = 4;</code>
   * @return Whether the toClient field is set.
   */
  boolean hasToClient();
  /**
   * <code>optional string toClient = 4;</code>
   * @return The toClient.
   */
  java.lang.String getToClient();
  /**
   * <code>optional string toClient = 4;</code>
   * @return The bytes for toClient.
   */
  com.google.protobuf.ByteString
      getToClientBytes();

  /**
   * <code>optional string groupId = 5;</code>
   * @return Whether the groupId field is set.
   */
  boolean hasGroupId();
  /**
   * <code>optional string groupId = 5;</code>
   * @return The groupId.
   */
  java.lang.String getGroupId();
  /**
   * <code>optional string groupId = 5;</code>
   * @return The bytes for groupId.
   */
  com.google.protobuf.ByteString
      getGroupIdBytes();

  /**
   * <code>optional int64 msgId = 6;</code>
   * @return Whether the msgId field is set.
   */
  boolean hasMsgId();
  /**
   * <code>optional int64 msgId = 6;</code>
   * @return The msgId.
   */
  long getMsgId();

  /**
   * <code>int32 seq = 7;</code>
   * @return The seq.
   */
  int getSeq();

  /**
   * <code>int32 ack = 8;</code>
   * @return The ack.
   */
  int getAck();

  /**
   * <code>string content = 9;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 9;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
