// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

// Protobuf Java Version: 4.26.1
package com.hibob.anyim.netty.protobuf;

public interface BodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hibob.anyim.netty.protobuf.Body)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 fromId = 1;</code>
   * @return The fromId.
   */
  int getFromId();

  /**
   * <code>int32 fromDev = 2;</code>
   * @return The fromDev.
   */
  int getFromDev();

  /**
   * <code>int32 toId = 3;</code>
   * @return The toId.
   */
  int getToId();

  /**
   * <code>int32 toDev = 4;</code>
   * @return The toDev.
   */
  int getToDev();

  /**
   * <code>int32 seq = 5;</code>
   * @return The seq.
   */
  int getSeq();

  /**
   * <code>string content = 6;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 6;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
