// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

// Protobuf Java Version: 4.26.1
package com.hibob.anyim.netty.protobuf;

public interface BodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hibob.anyim.netty.protobuf.Body)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string fromId = 1;</code>
   * @return Whether the fromId field is set.
   */
  boolean hasFromId();
  /**
   * <code>optional string fromId = 1;</code>
   * @return The fromId.
   */
  java.lang.String getFromId();
  /**
   * <code>optional string fromId = 1;</code>
   * @return The bytes for fromId.
   */
  com.google.protobuf.ByteString
      getFromIdBytes();

  /**
   * <code>optional string fromClient = 2;</code>
   * @return Whether the fromClient field is set.
   */
  boolean hasFromClient();
  /**
   * <code>optional string fromClient = 2;</code>
   * @return The fromClient.
   */
  java.lang.String getFromClient();
  /**
   * <code>optional string fromClient = 2;</code>
   * @return The bytes for fromClient.
   */
  com.google.protobuf.ByteString
      getFromClientBytes();

  /**
   * <code>optional string toId = 3;</code>
   * @return Whether the toId field is set.
   */
  boolean hasToId();
  /**
   * <code>optional string toId = 3;</code>
   * @return The toId.
   */
  java.lang.String getToId();
  /**
   * <code>optional string toId = 3;</code>
   * @return The bytes for toId.
   */
  com.google.protobuf.ByteString
      getToIdBytes();

  /**
   * <code>optional string toClient = 4;</code>
   * @return Whether the toClient field is set.
   */
  boolean hasToClient();
  /**
   * <code>optional string toClient = 4;</code>
   * @return The toClient.
   */
  java.lang.String getToClient();
  /**
   * <code>optional string toClient = 4;</code>
   * @return The bytes for toClient.
   */
  com.google.protobuf.ByteString
      getToClientBytes();

  /**
   * <code>optional int64 groupId = 5;</code>
   * @return Whether the groupId field is set.
   */
  boolean hasGroupId();
  /**
   * <code>optional int64 groupId = 5;</code>
   * @return The groupId.
   */
  long getGroupId();

  /**
   * <code>optional int64 msgId = 6;</code>
   * @return Whether the msgId field is set.
   */
  boolean hasMsgId();
  /**
   * <code>optional int64 msgId = 6;</code>
   * @return The msgId.
   */
  long getMsgId();

  /**
   * <code>optional int32 seq = 7;</code>
   * @return Whether the seq field is set.
   */
  boolean hasSeq();
  /**
   * <code>optional int32 seq = 7;</code>
   * @return The seq.
   */
  int getSeq();

  /**
   * <code>optional int32 ack = 8;</code>
   * @return Whether the ack field is set.
   */
  boolean hasAck();
  /**
   * <code>optional int32 ack = 8;</code>
   * @return The ack.
   */
  int getAck();

  /**
   * <code>optional string content = 9;</code>
   * @return Whether the content field is set.
   */
  boolean hasContent();
  /**
   * <code>optional string content = 9;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>optional string content = 9;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * 客户端生成的临时msgId，不能用于消息排序，所以必须照服务端换正式的msgId
   * </pre>
   *
   * <code>optional string tempMsgId = 10;</code>
   * @return Whether the tempMsgId field is set.
   */
  boolean hasTempMsgId();
  /**
   * <pre>
   * 客户端生成的临时msgId，不能用于消息排序，所以必须照服务端换正式的msgId
   * </pre>
   *
   * <code>optional string tempMsgId = 10;</code>
   * @return The tempMsgId.
   */
  java.lang.String getTempMsgId();
  /**
   * <pre>
   * 客户端生成的临时msgId，不能用于消息排序，所以必须照服务端换正式的msgId
   * </pre>
   *
   * <code>optional string tempMsgId = 10;</code>
   * @return The bytes for tempMsgId.
   */
  com.google.protobuf.ByteString
      getTempMsgIdBytes();

  /**
   * <pre>
   * MsgType=SENDER_SYNC需带上该字段，因为此时fromId和toId都是发送端的账号，无法识别是哪个session
   * </pre>
   *
   * <code>optional string sessionId = 11;</code>
   * @return Whether the sessionId field is set.
   */
  boolean hasSessionId();
  /**
   * <pre>
   * MsgType=SENDER_SYNC需带上该字段，因为此时fromId和toId都是发送端的账号，无法识别是哪个session
   * </pre>
   *
   * <code>optional string sessionId = 11;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <pre>
   * MsgType=SENDER_SYNC需带上该字段，因为此时fromId和toId都是发送端的账号，无法识别是哪个session
   * </pre>
   *
   * <code>optional string sessionId = 11;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();
}
