// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

// Protobuf Java Version: 4.26.1
package com.hibob.anyim.netty.protobuf;

/**
 * Protobuf type {@code com.hibob.anyim.netty.protobuf.Body}
 */
public final class Body extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.hibob.anyim.netty.protobuf.Body)
    BodyOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Body.class.getName());
  }
  // Use Body.newBuilder() to construct.
  private Body(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Body() {
    fromId_ = "";
    fromClient_ = "";
    toId_ = "";
    toClient_ = "";
    content_ = "";
    tempMsgId_ = "";
    sessionId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hibob.anyim.netty.protobuf.MsgOuterClass.internal_static_com_hibob_anyim_netty_protobuf_Body_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hibob.anyim.netty.protobuf.MsgOuterClass.internal_static_com_hibob_anyim_netty_protobuf_Body_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hibob.anyim.netty.protobuf.Body.class, com.hibob.anyim.netty.protobuf.Body.Builder.class);
  }

  private int bitField0_;
  public static final int FROMID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object fromId_ = "";
  /**
   * <code>optional string fromId = 1;</code>
   * @return Whether the fromId field is set.
   */
  @java.lang.Override
  public boolean hasFromId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string fromId = 1;</code>
   * @return The fromId.
   */
  @java.lang.Override
  public java.lang.String getFromId() {
    java.lang.Object ref = fromId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fromId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string fromId = 1;</code>
   * @return The bytes for fromId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFromIdBytes() {
    java.lang.Object ref = fromId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fromId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FROMCLIENT_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object fromClient_ = "";
  /**
   * <code>optional string fromClient = 2;</code>
   * @return Whether the fromClient field is set.
   */
  @java.lang.Override
  public boolean hasFromClient() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string fromClient = 2;</code>
   * @return The fromClient.
   */
  @java.lang.Override
  public java.lang.String getFromClient() {
    java.lang.Object ref = fromClient_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fromClient_ = s;
      return s;
    }
  }
  /**
   * <code>optional string fromClient = 2;</code>
   * @return The bytes for fromClient.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFromClientBytes() {
    java.lang.Object ref = fromClient_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fromClient_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object toId_ = "";
  /**
   * <code>optional string toId = 3;</code>
   * @return Whether the toId field is set.
   */
  @java.lang.Override
  public boolean hasToId() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string toId = 3;</code>
   * @return The toId.
   */
  @java.lang.Override
  public java.lang.String getToId() {
    java.lang.Object ref = toId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      toId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string toId = 3;</code>
   * @return The bytes for toId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getToIdBytes() {
    java.lang.Object ref = toId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      toId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOCLIENT_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object toClient_ = "";
  /**
   * <code>optional string toClient = 4;</code>
   * @return Whether the toClient field is set.
   */
  @java.lang.Override
  public boolean hasToClient() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string toClient = 4;</code>
   * @return The toClient.
   */
  @java.lang.Override
  public java.lang.String getToClient() {
    java.lang.Object ref = toClient_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      toClient_ = s;
      return s;
    }
  }
  /**
   * <code>optional string toClient = 4;</code>
   * @return The bytes for toClient.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getToClientBytes() {
    java.lang.Object ref = toClient_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      toClient_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GROUPID_FIELD_NUMBER = 5;
  private long groupId_ = 0L;
  /**
   * <code>optional int64 groupId = 5;</code>
   * @return Whether the groupId field is set.
   */
  @java.lang.Override
  public boolean hasGroupId() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional int64 groupId = 5;</code>
   * @return The groupId.
   */
  @java.lang.Override
  public long getGroupId() {
    return groupId_;
  }

  public static final int MSGID_FIELD_NUMBER = 6;
  private long msgId_ = 0L;
  /**
   * <code>optional int64 msgId = 6;</code>
   * @return Whether the msgId field is set.
   */
  @java.lang.Override
  public boolean hasMsgId() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional int64 msgId = 6;</code>
   * @return The msgId.
   */
  @java.lang.Override
  public long getMsgId() {
    return msgId_;
  }

  public static final int SEQ_FIELD_NUMBER = 7;
  private int seq_ = 0;
  /**
   * <code>optional int32 seq = 7;</code>
   * @return Whether the seq field is set.
   */
  @java.lang.Override
  public boolean hasSeq() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional int32 seq = 7;</code>
   * @return The seq.
   */
  @java.lang.Override
  public int getSeq() {
    return seq_;
  }

  public static final int ACK_FIELD_NUMBER = 8;
  private int ack_ = 0;
  /**
   * <code>optional int32 ack = 8;</code>
   * @return Whether the ack field is set.
   */
  @java.lang.Override
  public boolean hasAck() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional int32 ack = 8;</code>
   * @return The ack.
   */
  @java.lang.Override
  public int getAck() {
    return ack_;
  }

  public static final int CONTENT_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object content_ = "";
  /**
   * <code>optional string content = 9;</code>
   * @return Whether the content field is set.
   */
  @java.lang.Override
  public boolean hasContent() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <code>optional string content = 9;</code>
   * @return The content.
   */
  @java.lang.Override
  public java.lang.String getContent() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <code>optional string content = 9;</code>
   * @return The bytes for content.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentBytes() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEMPMSGID_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tempMsgId_ = "";
  /**
   * <pre>
   * 客户端生成的临时msgId，不能用于消息排序，所以必须照服务端换正式的msgId
   * </pre>
   *
   * <code>optional string tempMsgId = 10;</code>
   * @return Whether the tempMsgId field is set.
   */
  @java.lang.Override
  public boolean hasTempMsgId() {
    return ((bitField0_ & 0x00000200) != 0);
  }
  /**
   * <pre>
   * 客户端生成的临时msgId，不能用于消息排序，所以必须照服务端换正式的msgId
   * </pre>
   *
   * <code>optional string tempMsgId = 10;</code>
   * @return The tempMsgId.
   */
  @java.lang.Override
  public java.lang.String getTempMsgId() {
    java.lang.Object ref = tempMsgId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tempMsgId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 客户端生成的临时msgId，不能用于消息排序，所以必须照服务端换正式的msgId
   * </pre>
   *
   * <code>optional string tempMsgId = 10;</code>
   * @return The bytes for tempMsgId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTempMsgIdBytes() {
    java.lang.Object ref = tempMsgId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tempMsgId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SESSIONID_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sessionId_ = "";
  /**
   * <pre>
   * MsgType=SENDER_SYNC需带上该字段，因为此时fromId和toId都是发送端的账号，无法识别是哪个session
   * </pre>
   *
   * <code>optional string sessionId = 11;</code>
   * @return Whether the sessionId field is set.
   */
  @java.lang.Override
  public boolean hasSessionId() {
    return ((bitField0_ & 0x00000400) != 0);
  }
  /**
   * <pre>
   * MsgType=SENDER_SYNC需带上该字段，因为此时fromId和toId都是发送端的账号，无法识别是哪个session
   * </pre>
   *
   * <code>optional string sessionId = 11;</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * MsgType=SENDER_SYNC需带上该字段，因为此时fromId和toId都是发送端的账号，无法识别是哪个session
   * </pre>
   *
   * <code>optional string sessionId = 11;</code>
   * @return The bytes for sessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, fromId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, fromClient_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, toId_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, toClient_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt64(5, groupId_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeInt64(6, msgId_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeInt32(7, seq_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeInt32(8, ack_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, content_);
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, tempMsgId_);
    }
    if (((bitField0_ & 0x00000400) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 11, sessionId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, fromId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, fromClient_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, toId_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, toClient_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, groupId_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, msgId_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, seq_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, ack_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, content_);
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, tempMsgId_);
    }
    if (((bitField0_ & 0x00000400) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(11, sessionId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hibob.anyim.netty.protobuf.Body)) {
      return super.equals(obj);
    }
    com.hibob.anyim.netty.protobuf.Body other = (com.hibob.anyim.netty.protobuf.Body) obj;

    if (hasFromId() != other.hasFromId()) return false;
    if (hasFromId()) {
      if (!getFromId()
          .equals(other.getFromId())) return false;
    }
    if (hasFromClient() != other.hasFromClient()) return false;
    if (hasFromClient()) {
      if (!getFromClient()
          .equals(other.getFromClient())) return false;
    }
    if (hasToId() != other.hasToId()) return false;
    if (hasToId()) {
      if (!getToId()
          .equals(other.getToId())) return false;
    }
    if (hasToClient() != other.hasToClient()) return false;
    if (hasToClient()) {
      if (!getToClient()
          .equals(other.getToClient())) return false;
    }
    if (hasGroupId() != other.hasGroupId()) return false;
    if (hasGroupId()) {
      if (getGroupId()
          != other.getGroupId()) return false;
    }
    if (hasMsgId() != other.hasMsgId()) return false;
    if (hasMsgId()) {
      if (getMsgId()
          != other.getMsgId()) return false;
    }
    if (hasSeq() != other.hasSeq()) return false;
    if (hasSeq()) {
      if (getSeq()
          != other.getSeq()) return false;
    }
    if (hasAck() != other.hasAck()) return false;
    if (hasAck()) {
      if (getAck()
          != other.getAck()) return false;
    }
    if (hasContent() != other.hasContent()) return false;
    if (hasContent()) {
      if (!getContent()
          .equals(other.getContent())) return false;
    }
    if (hasTempMsgId() != other.hasTempMsgId()) return false;
    if (hasTempMsgId()) {
      if (!getTempMsgId()
          .equals(other.getTempMsgId())) return false;
    }
    if (hasSessionId() != other.hasSessionId()) return false;
    if (hasSessionId()) {
      if (!getSessionId()
          .equals(other.getSessionId())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasFromId()) {
      hash = (37 * hash) + FROMID_FIELD_NUMBER;
      hash = (53 * hash) + getFromId().hashCode();
    }
    if (hasFromClient()) {
      hash = (37 * hash) + FROMCLIENT_FIELD_NUMBER;
      hash = (53 * hash) + getFromClient().hashCode();
    }
    if (hasToId()) {
      hash = (37 * hash) + TOID_FIELD_NUMBER;
      hash = (53 * hash) + getToId().hashCode();
    }
    if (hasToClient()) {
      hash = (37 * hash) + TOCLIENT_FIELD_NUMBER;
      hash = (53 * hash) + getToClient().hashCode();
    }
    if (hasGroupId()) {
      hash = (37 * hash) + GROUPID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGroupId());
    }
    if (hasMsgId()) {
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgId());
    }
    if (hasSeq()) {
      hash = (37 * hash) + SEQ_FIELD_NUMBER;
      hash = (53 * hash) + getSeq();
    }
    if (hasAck()) {
      hash = (37 * hash) + ACK_FIELD_NUMBER;
      hash = (53 * hash) + getAck();
    }
    if (hasContent()) {
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
    }
    if (hasTempMsgId()) {
      hash = (37 * hash) + TEMPMSGID_FIELD_NUMBER;
      hash = (53 * hash) + getTempMsgId().hashCode();
    }
    if (hasSessionId()) {
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionId().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hibob.anyim.netty.protobuf.Body parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hibob.anyim.netty.protobuf.Body parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hibob.anyim.netty.protobuf.Body parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hibob.anyim.netty.protobuf.Body parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hibob.anyim.netty.protobuf.Body parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hibob.anyim.netty.protobuf.Body parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hibob.anyim.netty.protobuf.Body parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.hibob.anyim.netty.protobuf.Body parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.hibob.anyim.netty.protobuf.Body parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.hibob.anyim.netty.protobuf.Body parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hibob.anyim.netty.protobuf.Body parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.hibob.anyim.netty.protobuf.Body parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hibob.anyim.netty.protobuf.Body prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.hibob.anyim.netty.protobuf.Body}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.hibob.anyim.netty.protobuf.Body)
      com.hibob.anyim.netty.protobuf.BodyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hibob.anyim.netty.protobuf.MsgOuterClass.internal_static_com_hibob_anyim_netty_protobuf_Body_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hibob.anyim.netty.protobuf.MsgOuterClass.internal_static_com_hibob_anyim_netty_protobuf_Body_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hibob.anyim.netty.protobuf.Body.class, com.hibob.anyim.netty.protobuf.Body.Builder.class);
    }

    // Construct using com.hibob.anyim.netty.protobuf.Body.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      fromId_ = "";
      fromClient_ = "";
      toId_ = "";
      toClient_ = "";
      groupId_ = 0L;
      msgId_ = 0L;
      seq_ = 0;
      ack_ = 0;
      content_ = "";
      tempMsgId_ = "";
      sessionId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hibob.anyim.netty.protobuf.MsgOuterClass.internal_static_com_hibob_anyim_netty_protobuf_Body_descriptor;
    }

    @java.lang.Override
    public com.hibob.anyim.netty.protobuf.Body getDefaultInstanceForType() {
      return com.hibob.anyim.netty.protobuf.Body.getDefaultInstance();
    }

    @java.lang.Override
    public com.hibob.anyim.netty.protobuf.Body build() {
      com.hibob.anyim.netty.protobuf.Body result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hibob.anyim.netty.protobuf.Body buildPartial() {
      com.hibob.anyim.netty.protobuf.Body result = new com.hibob.anyim.netty.protobuf.Body(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.hibob.anyim.netty.protobuf.Body result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.fromId_ = fromId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.fromClient_ = fromClient_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.toId_ = toId_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.toClient_ = toClient_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.groupId_ = groupId_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.msgId_ = msgId_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.seq_ = seq_;
        to_bitField0_ |= 0x00000040;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.ack_ = ack_;
        to_bitField0_ |= 0x00000080;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.content_ = content_;
        to_bitField0_ |= 0x00000100;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.tempMsgId_ = tempMsgId_;
        to_bitField0_ |= 0x00000200;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.sessionId_ = sessionId_;
        to_bitField0_ |= 0x00000400;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hibob.anyim.netty.protobuf.Body) {
        return mergeFrom((com.hibob.anyim.netty.protobuf.Body)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hibob.anyim.netty.protobuf.Body other) {
      if (other == com.hibob.anyim.netty.protobuf.Body.getDefaultInstance()) return this;
      if (other.hasFromId()) {
        fromId_ = other.fromId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasFromClient()) {
        fromClient_ = other.fromClient_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasToId()) {
        toId_ = other.toId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasToClient()) {
        toClient_ = other.toClient_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasGroupId()) {
        setGroupId(other.getGroupId());
      }
      if (other.hasMsgId()) {
        setMsgId(other.getMsgId());
      }
      if (other.hasSeq()) {
        setSeq(other.getSeq());
      }
      if (other.hasAck()) {
        setAck(other.getAck());
      }
      if (other.hasContent()) {
        content_ = other.content_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (other.hasTempMsgId()) {
        tempMsgId_ = other.tempMsgId_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (other.hasSessionId()) {
        sessionId_ = other.sessionId_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              fromId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              fromClient_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              toId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              toClient_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              groupId_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              msgId_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              seq_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              ack_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 74: {
              content_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              tempMsgId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              sessionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object fromId_ = "";
    /**
     * <code>optional string fromId = 1;</code>
     * @return Whether the fromId field is set.
     */
    public boolean hasFromId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string fromId = 1;</code>
     * @return The fromId.
     */
    public java.lang.String getFromId() {
      java.lang.Object ref = fromId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string fromId = 1;</code>
     * @return The bytes for fromId.
     */
    public com.google.protobuf.ByteString
        getFromIdBytes() {
      java.lang.Object ref = fromId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string fromId = 1;</code>
     * @param value The fromId to set.
     * @return This builder for chaining.
     */
    public Builder setFromId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      fromId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional string fromId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFromId() {
      fromId_ = getDefaultInstance().getFromId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>optional string fromId = 1;</code>
     * @param value The bytes for fromId to set.
     * @return This builder for chaining.
     */
    public Builder setFromIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      fromId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object fromClient_ = "";
    /**
     * <code>optional string fromClient = 2;</code>
     * @return Whether the fromClient field is set.
     */
    public boolean hasFromClient() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string fromClient = 2;</code>
     * @return The fromClient.
     */
    public java.lang.String getFromClient() {
      java.lang.Object ref = fromClient_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromClient_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string fromClient = 2;</code>
     * @return The bytes for fromClient.
     */
    public com.google.protobuf.ByteString
        getFromClientBytes() {
      java.lang.Object ref = fromClient_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromClient_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string fromClient = 2;</code>
     * @param value The fromClient to set.
     * @return This builder for chaining.
     */
    public Builder setFromClient(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      fromClient_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string fromClient = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFromClient() {
      fromClient_ = getDefaultInstance().getFromClient();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string fromClient = 2;</code>
     * @param value The bytes for fromClient to set.
     * @return This builder for chaining.
     */
    public Builder setFromClientBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      fromClient_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object toId_ = "";
    /**
     * <code>optional string toId = 3;</code>
     * @return Whether the toId field is set.
     */
    public boolean hasToId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string toId = 3;</code>
     * @return The toId.
     */
    public java.lang.String getToId() {
      java.lang.Object ref = toId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string toId = 3;</code>
     * @return The bytes for toId.
     */
    public com.google.protobuf.ByteString
        getToIdBytes() {
      java.lang.Object ref = toId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string toId = 3;</code>
     * @param value The toId to set.
     * @return This builder for chaining.
     */
    public Builder setToId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      toId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional string toId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearToId() {
      toId_ = getDefaultInstance().getToId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>optional string toId = 3;</code>
     * @param value The bytes for toId to set.
     * @return This builder for chaining.
     */
    public Builder setToIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      toId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object toClient_ = "";
    /**
     * <code>optional string toClient = 4;</code>
     * @return Whether the toClient field is set.
     */
    public boolean hasToClient() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string toClient = 4;</code>
     * @return The toClient.
     */
    public java.lang.String getToClient() {
      java.lang.Object ref = toClient_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toClient_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string toClient = 4;</code>
     * @return The bytes for toClient.
     */
    public com.google.protobuf.ByteString
        getToClientBytes() {
      java.lang.Object ref = toClient_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toClient_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string toClient = 4;</code>
     * @param value The toClient to set.
     * @return This builder for chaining.
     */
    public Builder setToClient(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      toClient_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional string toClient = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearToClient() {
      toClient_ = getDefaultInstance().getToClient();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>optional string toClient = 4;</code>
     * @param value The bytes for toClient to set.
     * @return This builder for chaining.
     */
    public Builder setToClientBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      toClient_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private long groupId_ ;
    /**
     * <code>optional int64 groupId = 5;</code>
     * @return Whether the groupId field is set.
     */
    @java.lang.Override
    public boolean hasGroupId() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int64 groupId = 5;</code>
     * @return The groupId.
     */
    @java.lang.Override
    public long getGroupId() {
      return groupId_;
    }
    /**
     * <code>optional int64 groupId = 5;</code>
     * @param value The groupId to set.
     * @return This builder for chaining.
     */
    public Builder setGroupId(long value) {

      groupId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 groupId = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupId() {
      bitField0_ = (bitField0_ & ~0x00000010);
      groupId_ = 0L;
      onChanged();
      return this;
    }

    private long msgId_ ;
    /**
     * <code>optional int64 msgId = 6;</code>
     * @return Whether the msgId field is set.
     */
    @java.lang.Override
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional int64 msgId = 6;</code>
     * @return The msgId.
     */
    @java.lang.Override
    public long getMsgId() {
      return msgId_;
    }
    /**
     * <code>optional int64 msgId = 6;</code>
     * @param value The msgId to set.
     * @return This builder for chaining.
     */
    public Builder setMsgId(long value) {

      msgId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 msgId = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgId() {
      bitField0_ = (bitField0_ & ~0x00000020);
      msgId_ = 0L;
      onChanged();
      return this;
    }

    private int seq_ ;
    /**
     * <code>optional int32 seq = 7;</code>
     * @return Whether the seq field is set.
     */
    @java.lang.Override
    public boolean hasSeq() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional int32 seq = 7;</code>
     * @return The seq.
     */
    @java.lang.Override
    public int getSeq() {
      return seq_;
    }
    /**
     * <code>optional int32 seq = 7;</code>
     * @param value The seq to set.
     * @return This builder for chaining.
     */
    public Builder setSeq(int value) {

      seq_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 seq = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeq() {
      bitField0_ = (bitField0_ & ~0x00000040);
      seq_ = 0;
      onChanged();
      return this;
    }

    private int ack_ ;
    /**
     * <code>optional int32 ack = 8;</code>
     * @return Whether the ack field is set.
     */
    @java.lang.Override
    public boolean hasAck() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional int32 ack = 8;</code>
     * @return The ack.
     */
    @java.lang.Override
    public int getAck() {
      return ack_;
    }
    /**
     * <code>optional int32 ack = 8;</code>
     * @param value The ack to set.
     * @return This builder for chaining.
     */
    public Builder setAck(int value) {

      ack_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 ack = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearAck() {
      bitField0_ = (bitField0_ & ~0x00000080);
      ack_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object content_ = "";
    /**
     * <code>optional string content = 9;</code>
     * @return Whether the content field is set.
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional string content = 9;</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string content = 9;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string content = 9;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      content_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>optional string content = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      content_ = getDefaultInstance().getContent();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>optional string content = 9;</code>
     * @param value The bytes for content to set.
     * @return This builder for chaining.
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      content_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object tempMsgId_ = "";
    /**
     * <pre>
     * 客户端生成的临时msgId，不能用于消息排序，所以必须照服务端换正式的msgId
     * </pre>
     *
     * <code>optional string tempMsgId = 10;</code>
     * @return Whether the tempMsgId field is set.
     */
    public boolean hasTempMsgId() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <pre>
     * 客户端生成的临时msgId，不能用于消息排序，所以必须照服务端换正式的msgId
     * </pre>
     *
     * <code>optional string tempMsgId = 10;</code>
     * @return The tempMsgId.
     */
    public java.lang.String getTempMsgId() {
      java.lang.Object ref = tempMsgId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tempMsgId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 客户端生成的临时msgId，不能用于消息排序，所以必须照服务端换正式的msgId
     * </pre>
     *
     * <code>optional string tempMsgId = 10;</code>
     * @return The bytes for tempMsgId.
     */
    public com.google.protobuf.ByteString
        getTempMsgIdBytes() {
      java.lang.Object ref = tempMsgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tempMsgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 客户端生成的临时msgId，不能用于消息排序，所以必须照服务端换正式的msgId
     * </pre>
     *
     * <code>optional string tempMsgId = 10;</code>
     * @param value The tempMsgId to set.
     * @return This builder for chaining.
     */
    public Builder setTempMsgId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tempMsgId_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 客户端生成的临时msgId，不能用于消息排序，所以必须照服务端换正式的msgId
     * </pre>
     *
     * <code>optional string tempMsgId = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearTempMsgId() {
      tempMsgId_ = getDefaultInstance().getTempMsgId();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 客户端生成的临时msgId，不能用于消息排序，所以必须照服务端换正式的msgId
     * </pre>
     *
     * <code>optional string tempMsgId = 10;</code>
     * @param value The bytes for tempMsgId to set.
     * @return This builder for chaining.
     */
    public Builder setTempMsgIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tempMsgId_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private java.lang.Object sessionId_ = "";
    /**
     * <pre>
     * MsgType=SENDER_SYNC需带上该字段，因为此时fromId和toId都是发送端的账号，无法识别是哪个session
     * </pre>
     *
     * <code>optional string sessionId = 11;</code>
     * @return Whether the sessionId field is set.
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <pre>
     * MsgType=SENDER_SYNC需带上该字段，因为此时fromId和toId都是发送端的账号，无法识别是哪个session
     * </pre>
     *
     * <code>optional string sessionId = 11;</code>
     * @return The sessionId.
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * MsgType=SENDER_SYNC需带上该字段，因为此时fromId和toId都是发送端的账号，无法识别是哪个session
     * </pre>
     *
     * <code>optional string sessionId = 11;</code>
     * @return The bytes for sessionId.
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * MsgType=SENDER_SYNC需带上该字段，因为此时fromId和toId都是发送端的账号，无法识别是哪个session
     * </pre>
     *
     * <code>optional string sessionId = 11;</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sessionId_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * MsgType=SENDER_SYNC需带上该字段，因为此时fromId和toId都是发送端的账号，无法识别是哪个session
     * </pre>
     *
     * <code>optional string sessionId = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      sessionId_ = getDefaultInstance().getSessionId();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * MsgType=SENDER_SYNC需带上该字段，因为此时fromId和toId都是发送端的账号，无法识别是哪个session
     * </pre>
     *
     * <code>optional string sessionId = 11;</code>
     * @param value The bytes for sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sessionId_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.hibob.anyim.netty.protobuf.Body)
  }

  // @@protoc_insertion_point(class_scope:com.hibob.anyim.netty.protobuf.Body)
  private static final com.hibob.anyim.netty.protobuf.Body DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hibob.anyim.netty.protobuf.Body();
  }

  public static com.hibob.anyim.netty.protobuf.Body getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Body>
      PARSER = new com.google.protobuf.AbstractParser<Body>() {
    @java.lang.Override
    public Body parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Body> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Body> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hibob.anyim.netty.protobuf.Body getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

