// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

// Protobuf Java Version: 4.26.1
package com.hibob.anyim.netty.protobuf;

public interface ChatBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hibob.anyim.netty.protobuf.ChatBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fromId = 1;</code>
   * @return The fromId.
   */
  java.lang.String getFromId();
  /**
   * <code>string fromId = 1;</code>
   * @return The bytes for fromId.
   */
  com.google.protobuf.ByteString
      getFromIdBytes();

  /**
   * <code>string fromDev = 2;</code>
   * @return The fromDev.
   */
  java.lang.String getFromDev();
  /**
   * <code>string fromDev = 2;</code>
   * @return The bytes for fromDev.
   */
  com.google.protobuf.ByteString
      getFromDevBytes();

  /**
   * <code>string toId = 3;</code>
   * @return The toId.
   */
  java.lang.String getToId();
  /**
   * <code>string toId = 3;</code>
   * @return The bytes for toId.
   */
  com.google.protobuf.ByteString
      getToIdBytes();

  /**
   * <code>string toDev = 4;</code>
   * @return The toDev.
   */
  java.lang.String getToDev();
  /**
   * <code>string toDev = 4;</code>
   * @return The bytes for toDev.
   */
  com.google.protobuf.ByteString
      getToDevBytes();

  /**
   * <code>int32 seq = 5;</code>
   * @return The seq.
   */
  int getSeq();

  /**
   * <code>string content = 6;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 6;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
