// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

// Protobuf Java Version: 4.26.1
package com.hibob.anyim.netty.protobuf;

/**
 * Protobuf type {@code com.hibob.anyim.netty.protobuf.Extension}
 */
public final class Extension extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.hibob.anyim.netty.protobuf.Extension)
    ExtensionOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Extension.class.getName());
  }
  // Use Extension.newBuilder() to construct.
  private Extension(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Extension() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hibob.anyim.netty.protobuf.MsgOuterClass.internal_static_com_hibob_anyim_netty_protobuf_Extension_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 1:
        return internalGetExtensionMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hibob.anyim.netty.protobuf.MsgOuterClass.internal_static_com_hibob_anyim_netty_protobuf_Extension_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hibob.anyim.netty.protobuf.Extension.class, com.hibob.anyim.netty.protobuf.Extension.Builder.class);
  }

  public static final int EXTENSIONMAP_FIELD_NUMBER = 1;
  private static final class ExtensionMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.hibob.anyim.netty.protobuf.MsgOuterClass.internal_static_com_hibob_anyim_netty_protobuf_Extension_ExtensionMapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> extensionMap_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetExtensionMap() {
    if (extensionMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ExtensionMapDefaultEntryHolder.defaultEntry);
    }
    return extensionMap_;
  }
  public int getExtensionMapCount() {
    return internalGetExtensionMap().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; extensionMap = 1;</code>
   */
  @java.lang.Override
  public boolean containsExtensionMap(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetExtensionMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getExtensionMapMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getExtensionMap() {
    return getExtensionMapMap();
  }
  /**
   * <code>map&lt;string, string&gt; extensionMap = 1;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getExtensionMapMap() {
    return internalGetExtensionMap().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; extensionMap = 1;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getExtensionMapOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetExtensionMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; extensionMap = 1;</code>
   */
  @java.lang.Override
  public java.lang.String getExtensionMapOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetExtensionMap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetExtensionMap(),
        ExtensionMapDefaultEntryHolder.defaultEntry,
        1);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetExtensionMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      extensionMap__ = ExtensionMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, extensionMap__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hibob.anyim.netty.protobuf.Extension)) {
      return super.equals(obj);
    }
    com.hibob.anyim.netty.protobuf.Extension other = (com.hibob.anyim.netty.protobuf.Extension) obj;

    if (!internalGetExtensionMap().equals(
        other.internalGetExtensionMap())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetExtensionMap().getMap().isEmpty()) {
      hash = (37 * hash) + EXTENSIONMAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetExtensionMap().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hibob.anyim.netty.protobuf.Extension parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hibob.anyim.netty.protobuf.Extension parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hibob.anyim.netty.protobuf.Extension parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hibob.anyim.netty.protobuf.Extension parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hibob.anyim.netty.protobuf.Extension parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hibob.anyim.netty.protobuf.Extension parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hibob.anyim.netty.protobuf.Extension parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.hibob.anyim.netty.protobuf.Extension parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.hibob.anyim.netty.protobuf.Extension parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.hibob.anyim.netty.protobuf.Extension parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hibob.anyim.netty.protobuf.Extension parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.hibob.anyim.netty.protobuf.Extension parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hibob.anyim.netty.protobuf.Extension prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.hibob.anyim.netty.protobuf.Extension}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.hibob.anyim.netty.protobuf.Extension)
      com.hibob.anyim.netty.protobuf.ExtensionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hibob.anyim.netty.protobuf.MsgOuterClass.internal_static_com_hibob_anyim_netty_protobuf_Extension_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetExtensionMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableExtensionMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hibob.anyim.netty.protobuf.MsgOuterClass.internal_static_com_hibob_anyim_netty_protobuf_Extension_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hibob.anyim.netty.protobuf.Extension.class, com.hibob.anyim.netty.protobuf.Extension.Builder.class);
    }

    // Construct using com.hibob.anyim.netty.protobuf.Extension.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutableExtensionMap().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hibob.anyim.netty.protobuf.MsgOuterClass.internal_static_com_hibob_anyim_netty_protobuf_Extension_descriptor;
    }

    @java.lang.Override
    public com.hibob.anyim.netty.protobuf.Extension getDefaultInstanceForType() {
      return com.hibob.anyim.netty.protobuf.Extension.getDefaultInstance();
    }

    @java.lang.Override
    public com.hibob.anyim.netty.protobuf.Extension build() {
      com.hibob.anyim.netty.protobuf.Extension result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hibob.anyim.netty.protobuf.Extension buildPartial() {
      com.hibob.anyim.netty.protobuf.Extension result = new com.hibob.anyim.netty.protobuf.Extension(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.hibob.anyim.netty.protobuf.Extension result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.extensionMap_ = internalGetExtensionMap();
        result.extensionMap_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hibob.anyim.netty.protobuf.Extension) {
        return mergeFrom((com.hibob.anyim.netty.protobuf.Extension)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hibob.anyim.netty.protobuf.Extension other) {
      if (other == com.hibob.anyim.netty.protobuf.Extension.getDefaultInstance()) return this;
      internalGetMutableExtensionMap().mergeFrom(
          other.internalGetExtensionMap());
      bitField0_ |= 0x00000001;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              extensionMap__ = input.readMessage(
                  ExtensionMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableExtensionMap().getMutableMap().put(
                  extensionMap__.getKey(), extensionMap__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> extensionMap_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetExtensionMap() {
      if (extensionMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ExtensionMapDefaultEntryHolder.defaultEntry);
      }
      return extensionMap_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableExtensionMap() {
      if (extensionMap_ == null) {
        extensionMap_ = com.google.protobuf.MapField.newMapField(
            ExtensionMapDefaultEntryHolder.defaultEntry);
      }
      if (!extensionMap_.isMutable()) {
        extensionMap_ = extensionMap_.copy();
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return extensionMap_;
    }
    public int getExtensionMapCount() {
      return internalGetExtensionMap().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; extensionMap = 1;</code>
     */
    @java.lang.Override
    public boolean containsExtensionMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetExtensionMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getExtensionMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getExtensionMap() {
      return getExtensionMapMap();
    }
    /**
     * <code>map&lt;string, string&gt; extensionMap = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getExtensionMapMap() {
      return internalGetExtensionMap().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; extensionMap = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getExtensionMapOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetExtensionMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; extensionMap = 1;</code>
     */
    @java.lang.Override
    public java.lang.String getExtensionMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetExtensionMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearExtensionMap() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableExtensionMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; extensionMap = 1;</code>
     */
    public Builder removeExtensionMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableExtensionMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableExtensionMap() {
      bitField0_ |= 0x00000001;
      return internalGetMutableExtensionMap().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; extensionMap = 1;</code>
     */
    public Builder putExtensionMap(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableExtensionMap().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; extensionMap = 1;</code>
     */
    public Builder putAllExtensionMap(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableExtensionMap().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.hibob.anyim.netty.protobuf.Extension)
  }

  // @@protoc_insertion_point(class_scope:com.hibob.anyim.netty.protobuf.Extension)
  private static final com.hibob.anyim.netty.protobuf.Extension DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hibob.anyim.netty.protobuf.Extension();
  }

  public static com.hibob.anyim.netty.protobuf.Extension getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Extension>
      PARSER = new com.google.protobuf.AbstractParser<Extension>() {
    @java.lang.Override
    public Extension parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Extension> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Extension> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hibob.anyim.netty.protobuf.Extension getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

