// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

// Protobuf Java Version: 4.26.1
package com.hibob.anyim.netty.protobuf;

public interface ExtensionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hibob.anyim.netty.protobuf.Extension)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, string&gt; extensionMap = 1;</code>
   */
  int getExtensionMapCount();
  /**
   * <code>map&lt;string, string&gt; extensionMap = 1;</code>
   */
  boolean containsExtensionMap(
      java.lang.String key);
  /**
   * Use {@link #getExtensionMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getExtensionMap();
  /**
   * <code>map&lt;string, string&gt; extensionMap = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getExtensionMapMap();
  /**
   * <code>map&lt;string, string&gt; extensionMap = 1;</code>
   */
  /* nullable */
java.lang.String getExtensionMapOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; extensionMap = 1;</code>
   */
  java.lang.String getExtensionMapOrThrow(
      java.lang.String key);
}
