// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

// Protobuf Java Version: 4.26.1
package com.hibob.anyim.netty.protobuf;

public interface GroupChatBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hibob.anyim.netty.protobuf.GroupChatBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fromId = 1;</code>
   * @return The fromId.
   */
  java.lang.String getFromId();
  /**
   * <code>string fromId = 1;</code>
   * @return The bytes for fromId.
   */
  com.google.protobuf.ByteString
      getFromIdBytes();

  /**
   * <code>string fromDev = 2;</code>
   * @return The fromDev.
   */
  java.lang.String getFromDev();
  /**
   * <code>string fromDev = 2;</code>
   * @return The bytes for fromDev.
   */
  com.google.protobuf.ByteString
      getFromDevBytes();

  /**
   * <code>string toGroupId = 3;</code>
   * @return The toGroupId.
   */
  java.lang.String getToGroupId();
  /**
   * <code>string toGroupId = 3;</code>
   * @return The bytes for toGroupId.
   */
  com.google.protobuf.ByteString
      getToGroupIdBytes();

  /**
   * <code>int32 seq = 4;</code>
   * @return The seq.
   */
  int getSeq();

  /**
   * <code>string content = 5;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 5;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
