// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

// Protobuf Java Version: 4.26.1
package com.hibob.anyim.netty.protobuf;

/**
 * Protobuf type {@code com.hibob.anyim.netty.protobuf.Header}
 */
public final class Header extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.hibob.anyim.netty.protobuf.Header)
    HeaderOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Header.class.getName());
  }
  // Use Header.newBuilder() to construct.
  private Header(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Header() {
    msgType_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hibob.anyim.netty.protobuf.MsgOuterClass.internal_static_com_hibob_anyim_netty_protobuf_Header_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hibob.anyim.netty.protobuf.MsgOuterClass.internal_static_com_hibob_anyim_netty_protobuf_Header_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hibob.anyim.netty.protobuf.Header.class, com.hibob.anyim.netty.protobuf.Header.Builder.class);
  }

  public static final int MAGIC_FIELD_NUMBER = 1;
  private int magic_ = 0;
  /**
   * <code>int32 magic = 1;</code>
   * @return The magic.
   */
  @java.lang.Override
  public int getMagic() {
    return magic_;
  }

  public static final int VERSION_FIELD_NUMBER = 2;
  private int version_ = 0;
  /**
   * <code>int32 version = 2;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int MSGTYPE_FIELD_NUMBER = 3;
  private int msgType_ = 0;
  /**
   * <code>.com.hibob.anyim.netty.protobuf.MsgType msgType = 3;</code>
   * @return The enum numeric value on the wire for msgType.
   */
  @java.lang.Override public int getMsgTypeValue() {
    return msgType_;
  }
  /**
   * <code>.com.hibob.anyim.netty.protobuf.MsgType msgType = 3;</code>
   * @return The msgType.
   */
  @java.lang.Override public com.hibob.anyim.netty.protobuf.MsgType getMsgType() {
    com.hibob.anyim.netty.protobuf.MsgType result = com.hibob.anyim.netty.protobuf.MsgType.forNumber(msgType_);
    return result == null ? com.hibob.anyim.netty.protobuf.MsgType.UNRECOGNIZED : result;
  }

  public static final int ISEXTENSION_FIELD_NUMBER = 4;
  private boolean isExtension_ = false;
  /**
   * <code>bool isExtension = 4;</code>
   * @return The isExtension.
   */
  @java.lang.Override
  public boolean getIsExtension() {
    return isExtension_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (magic_ != 0) {
      output.writeInt32(1, magic_);
    }
    if (version_ != 0) {
      output.writeInt32(2, version_);
    }
    if (msgType_ != com.hibob.anyim.netty.protobuf.MsgType.HELLO.getNumber()) {
      output.writeEnum(3, msgType_);
    }
    if (isExtension_ != false) {
      output.writeBool(4, isExtension_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (magic_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, magic_);
    }
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, version_);
    }
    if (msgType_ != com.hibob.anyim.netty.protobuf.MsgType.HELLO.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, msgType_);
    }
    if (isExtension_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, isExtension_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hibob.anyim.netty.protobuf.Header)) {
      return super.equals(obj);
    }
    com.hibob.anyim.netty.protobuf.Header other = (com.hibob.anyim.netty.protobuf.Header) obj;

    if (getMagic()
        != other.getMagic()) return false;
    if (getVersion()
        != other.getVersion()) return false;
    if (msgType_ != other.msgType_) return false;
    if (getIsExtension()
        != other.getIsExtension()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MAGIC_FIELD_NUMBER;
    hash = (53 * hash) + getMagic();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
    hash = (53 * hash) + msgType_;
    hash = (37 * hash) + ISEXTENSION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsExtension());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hibob.anyim.netty.protobuf.Header parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hibob.anyim.netty.protobuf.Header parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hibob.anyim.netty.protobuf.Header parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hibob.anyim.netty.protobuf.Header parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hibob.anyim.netty.protobuf.Header parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hibob.anyim.netty.protobuf.Header parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hibob.anyim.netty.protobuf.Header parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.hibob.anyim.netty.protobuf.Header parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.hibob.anyim.netty.protobuf.Header parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.hibob.anyim.netty.protobuf.Header parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hibob.anyim.netty.protobuf.Header parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.hibob.anyim.netty.protobuf.Header parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hibob.anyim.netty.protobuf.Header prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.hibob.anyim.netty.protobuf.Header}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.hibob.anyim.netty.protobuf.Header)
      com.hibob.anyim.netty.protobuf.HeaderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hibob.anyim.netty.protobuf.MsgOuterClass.internal_static_com_hibob_anyim_netty_protobuf_Header_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hibob.anyim.netty.protobuf.MsgOuterClass.internal_static_com_hibob_anyim_netty_protobuf_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hibob.anyim.netty.protobuf.Header.class, com.hibob.anyim.netty.protobuf.Header.Builder.class);
    }

    // Construct using com.hibob.anyim.netty.protobuf.Header.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      magic_ = 0;
      version_ = 0;
      msgType_ = 0;
      isExtension_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hibob.anyim.netty.protobuf.MsgOuterClass.internal_static_com_hibob_anyim_netty_protobuf_Header_descriptor;
    }

    @java.lang.Override
    public com.hibob.anyim.netty.protobuf.Header getDefaultInstanceForType() {
      return com.hibob.anyim.netty.protobuf.Header.getDefaultInstance();
    }

    @java.lang.Override
    public com.hibob.anyim.netty.protobuf.Header build() {
      com.hibob.anyim.netty.protobuf.Header result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hibob.anyim.netty.protobuf.Header buildPartial() {
      com.hibob.anyim.netty.protobuf.Header result = new com.hibob.anyim.netty.protobuf.Header(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.hibob.anyim.netty.protobuf.Header result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.magic_ = magic_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.version_ = version_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.msgType_ = msgType_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.isExtension_ = isExtension_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hibob.anyim.netty.protobuf.Header) {
        return mergeFrom((com.hibob.anyim.netty.protobuf.Header)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hibob.anyim.netty.protobuf.Header other) {
      if (other == com.hibob.anyim.netty.protobuf.Header.getDefaultInstance()) return this;
      if (other.getMagic() != 0) {
        setMagic(other.getMagic());
      }
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.msgType_ != 0) {
        setMsgTypeValue(other.getMsgTypeValue());
      }
      if (other.getIsExtension() != false) {
        setIsExtension(other.getIsExtension());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              magic_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              version_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              msgType_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              isExtension_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int magic_ ;
    /**
     * <code>int32 magic = 1;</code>
     * @return The magic.
     */
    @java.lang.Override
    public int getMagic() {
      return magic_;
    }
    /**
     * <code>int32 magic = 1;</code>
     * @param value The magic to set.
     * @return This builder for chaining.
     */
    public Builder setMagic(int value) {

      magic_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 magic = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMagic() {
      bitField0_ = (bitField0_ & ~0x00000001);
      magic_ = 0;
      onChanged();
      return this;
    }

    private int version_ ;
    /**
     * <code>int32 version = 2;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 2;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {

      version_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000002);
      version_ = 0;
      onChanged();
      return this;
    }

    private int msgType_ = 0;
    /**
     * <code>.com.hibob.anyim.netty.protobuf.MsgType msgType = 3;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    @java.lang.Override public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <code>.com.hibob.anyim.netty.protobuf.MsgType msgType = 3;</code>
     * @param value The enum numeric value on the wire for msgType to set.
     * @return This builder for chaining.
     */
    public Builder setMsgTypeValue(int value) {
      msgType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.com.hibob.anyim.netty.protobuf.MsgType msgType = 3;</code>
     * @return The msgType.
     */
    @java.lang.Override
    public com.hibob.anyim.netty.protobuf.MsgType getMsgType() {
      com.hibob.anyim.netty.protobuf.MsgType result = com.hibob.anyim.netty.protobuf.MsgType.forNumber(msgType_);
      return result == null ? com.hibob.anyim.netty.protobuf.MsgType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.hibob.anyim.netty.protobuf.MsgType msgType = 3;</code>
     * @param value The msgType to set.
     * @return This builder for chaining.
     */
    public Builder setMsgType(com.hibob.anyim.netty.protobuf.MsgType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      msgType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.hibob.anyim.netty.protobuf.MsgType msgType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgType() {
      bitField0_ = (bitField0_ & ~0x00000004);
      msgType_ = 0;
      onChanged();
      return this;
    }

    private boolean isExtension_ ;
    /**
     * <code>bool isExtension = 4;</code>
     * @return The isExtension.
     */
    @java.lang.Override
    public boolean getIsExtension() {
      return isExtension_;
    }
    /**
     * <code>bool isExtension = 4;</code>
     * @param value The isExtension to set.
     * @return This builder for chaining.
     */
    public Builder setIsExtension(boolean value) {

      isExtension_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bool isExtension = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsExtension() {
      bitField0_ = (bitField0_ & ~0x00000008);
      isExtension_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.hibob.anyim.netty.protobuf.Header)
  }

  // @@protoc_insertion_point(class_scope:com.hibob.anyim.netty.protobuf.Header)
  private static final com.hibob.anyim.netty.protobuf.Header DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hibob.anyim.netty.protobuf.Header();
  }

  public static com.hibob.anyim.netty.protobuf.Header getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Header>
      PARSER = new com.google.protobuf.AbstractParser<Header>() {
    @java.lang.Override
    public Header parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Header> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Header> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hibob.anyim.netty.protobuf.Header getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

