// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

// Protobuf Java Version: 4.26.1
package com.hibob.anyim.netty.protobuf;

public interface HeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hibob.anyim.netty.protobuf.Header)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 magic = 1;</code>
   * @return The magic.
   */
  int getMagic();

  /**
   * <code>int32 version = 2;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>.com.hibob.anyim.netty.protobuf.MsgType msgType = 3;</code>
   * @return The enum numeric value on the wire for msgType.
   */
  int getMsgTypeValue();
  /**
   * <code>.com.hibob.anyim.netty.protobuf.MsgType msgType = 3;</code>
   * @return The msgType.
   */
  com.hibob.anyim.netty.protobuf.MsgType getMsgType();

  /**
   * <code>bool isExtension = 4;</code>
   * @return The isExtension.
   */
  boolean getIsExtension();
}
