// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto
// Protobuf Java Version: 4.26.1

package com.hibob.anyim.netty.protobuf;

public final class MsgOuterClass {
  private MsgOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      MsgOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hibob_anyim_netty_protobuf_Msg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hibob_anyim_netty_protobuf_Msg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hibob_anyim_netty_protobuf_Header_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hibob_anyim_netty_protobuf_Header_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hibob_anyim_netty_protobuf_Body_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hibob_anyim_netty_protobuf_Body_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hibob_anyim_netty_protobuf_Extension_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hibob_anyim_netty_protobuf_Extension_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hibob_anyim_netty_protobuf_Extension_ExtensionMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hibob_anyim_netty_protobuf_Extension_ExtensionMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmsg.proto\022\036com.hibob.anyim.netty.proto" +
      "buf\"\302\001\n\003Msg\0226\n\006header\030\001 \001(\0132&.com.hibob." +
      "anyim.netty.protobuf.Header\0222\n\004body\030\002 \001(" +
      "\0132$.com.hibob.anyim.netty.protobuf.Body\022" +
      "A\n\textension\030c \001(\0132).com.hibob.anyim.net" +
      "ty.protobuf.ExtensionH\000\210\001\001B\014\n\n_extension" +
      "\"w\n\006Header\022\r\n\005magic\030\001 \001(\005\022\017\n\007version\030\002 \001" +
      "(\005\0228\n\007msgType\030\003 \001(\0162\'.com.hibob.anyim.ne" +
      "tty.protobuf.MsgType\022\023\n\013isExtension\030\004 \001(" +
      "\010\"\325\001\n\004Body\022\016\n\006fromId\030\001 \001(\t\022\022\n\nfromClient" +
      "\030\002 \001(\t\022\021\n\004toId\030\003 \001(\tH\000\210\001\001\022\025\n\010toClient\030\004 " +
      "\001(\tH\001\210\001\001\022\024\n\007groupId\030\005 \001(\tH\002\210\001\001\022\022\n\005msgId\030" +
      "\006 \001(\003H\003\210\001\001\022\013\n\003seq\030\007 \001(\005\022\013\n\003ack\030\010 \001(\005\022\017\n\007" +
      "content\030\t \001(\tB\007\n\005_toIdB\013\n\t_toClientB\n\n\010_" +
      "groupIdB\010\n\006_msgId\"\223\001\n\tExtension\022Q\n\014exten" +
      "sionMap\030\001 \003(\0132;.com.hibob.anyim.netty.pr" +
      "otobuf.Extension.ExtensionMapEntry\0323\n\021Ex" +
      "tensionMapEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 " +
      "\001(\t:\0028\001*}\n\007MsgType\022\t\n\005HELLO\020\000\022\016\n\nHEART_B" +
      "EAT\020\001\022\010\n\004CHAT\020\002\022\016\n\nGROUP_CHAT\020\003\022\026\n\022CLOSE" +
      "_BY_READ_IDLE\020\n\022\030\n\024CLOSE_BY_ERROR_MAGIC\020" +
      "\013\022\013\n\007DEFAULT\020cB\"\n\036com.hibob.anyim.netty." +
      "protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_hibob_anyim_netty_protobuf_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hibob_anyim_netty_protobuf_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_hibob_anyim_netty_protobuf_Msg_descriptor,
        new java.lang.String[] { "Header", "Body", "Extension", });
    internal_static_com_hibob_anyim_netty_protobuf_Header_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_hibob_anyim_netty_protobuf_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_hibob_anyim_netty_protobuf_Header_descriptor,
        new java.lang.String[] { "Magic", "Version", "MsgType", "IsExtension", });
    internal_static_com_hibob_anyim_netty_protobuf_Body_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_hibob_anyim_netty_protobuf_Body_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_hibob_anyim_netty_protobuf_Body_descriptor,
        new java.lang.String[] { "FromId", "FromClient", "ToId", "ToClient", "GroupId", "MsgId", "Seq", "Ack", "Content", });
    internal_static_com_hibob_anyim_netty_protobuf_Extension_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_hibob_anyim_netty_protobuf_Extension_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_hibob_anyim_netty_protobuf_Extension_descriptor,
        new java.lang.String[] { "ExtensionMap", });
    internal_static_com_hibob_anyim_netty_protobuf_Extension_ExtensionMapEntry_descriptor =
      internal_static_com_hibob_anyim_netty_protobuf_Extension_descriptor.getNestedTypes().get(0);
    internal_static_com_hibob_anyim_netty_protobuf_Extension_ExtensionMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_hibob_anyim_netty_protobuf_Extension_ExtensionMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
