// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto
// Protobuf Java Version: 4.26.1

package com.hibob.anyim.common.protobuf;

public final class MsgOuterClass {
  private MsgOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      MsgOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hibob_anyim_common_protobuf_Msg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hibob_anyim_common_protobuf_Msg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hibob_anyim_common_protobuf_Header_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hibob_anyim_common_protobuf_Header_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hibob_anyim_common_protobuf_Body_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hibob_anyim_common_protobuf_Body_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hibob_anyim_common_protobuf_Extension_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hibob_anyim_common_protobuf_Extension_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hibob_anyim_common_protobuf_Extension_ExtensionMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hibob_anyim_common_protobuf_Extension_ExtensionMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmsg.proto\022\037com.hibob.anyim.common.prot" +
      "obuf\"\305\001\n\003Msg\0227\n\006header\030\001 \001(\0132\'.com.hibob" +
      ".anyim.common.protobuf.Header\0223\n\004body\030\002 " +
      "\001(\0132%.com.hibob.anyim.common.protobuf.Bo" +
      "dy\022B\n\textension\030c \001(\0132*.com.hibob.anyim." +
      "common.protobuf.ExtensionH\000\210\001\001B\014\n\n_exten" +
      "sion\"x\n\006Header\022\r\n\005magic\030\001 \001(\005\022\017\n\007version" +
      "\030\002 \001(\005\0229\n\007msgType\030\003 \001(\0162(.com.hibob.anyi" +
      "m.common.protobuf.MsgType\022\023\n\013isExtension" +
      "\030\004 \001(\010\"\360\002\n\004Body\022\023\n\006fromId\030\001 \001(\tH\000\210\001\001\022\027\n\n" +
      "fromClient\030\002 \001(\tH\001\210\001\001\022\021\n\004toId\030\003 \001(\tH\002\210\001\001" +
      "\022\025\n\010toClient\030\004 \001(\tH\003\210\001\001\022\024\n\007groupId\030\005 \001(\t" +
      "H\004\210\001\001\022\022\n\005msgId\030\006 \001(\003H\005\210\001\001\022\020\n\003seq\030\007 \001(\005H\006" +
      "\210\001\001\022\020\n\003ack\030\010 \001(\005H\007\210\001\001\022\024\n\007content\030\t \001(\tH\010" +
      "\210\001\001\022\026\n\ttempMsgId\030\n \001(\tH\t\210\001\001\022\026\n\tsessionId" +
      "\030\013 \001(\tH\n\210\001\001B\t\n\007_fromIdB\r\n\013_fromClientB\007\n" +
      "\005_toIdB\013\n\t_toClientB\n\n\010_groupIdB\010\n\006_msgI" +
      "dB\006\n\004_seqB\006\n\004_ackB\n\n\010_contentB\014\n\n_tempMs" +
      "gIdB\014\n\n_sessionId\"\224\001\n\tExtension\022R\n\014exten" +
      "sionMap\030\001 \003(\0132<.com.hibob.anyim.common.p" +
      "rotobuf.Extension.ExtensionMapEntry\0323\n\021E" +
      "xtensionMapEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002" +
      " \001(\t:\0028\001*\356\001\n\007MsgType\022\t\n\005HELLO\020\000\022\016\n\nHEART" +
      "_BEAT\020\001\022\010\n\004CHAT\020\002\022\016\n\nGROUP_CHAT\020\003\022\r\n\tCHA" +
      "T_READ\020\004\022\023\n\017GROUP_CHAT_READ\020\005\022\r\n\tDELIVER" +
      "ED\020\006\022\013\n\007RESERVE\020\007\022\016\n\nSTATUS_REQ\020\010\022\016\n\nSTA" +
      "TUS_RES\020\t\022\017\n\013STATUS_SYNC\020\n\022\026\n\022CLOSE_BY_R" +
      "EAD_IDLE\0202\022\030\n\024CLOSE_BY_ERROR_MAGIC\0203\022\013\n\007" +
      "DEFAULT\020cB#\n\037com.hibob.anyim.common.prot" +
      "obufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_hibob_anyim_common_protobuf_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hibob_anyim_common_protobuf_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_hibob_anyim_common_protobuf_Msg_descriptor,
        new java.lang.String[] { "Header", "Body", "Extension", });
    internal_static_com_hibob_anyim_common_protobuf_Header_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_hibob_anyim_common_protobuf_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_hibob_anyim_common_protobuf_Header_descriptor,
        new java.lang.String[] { "Magic", "Version", "MsgType", "IsExtension", });
    internal_static_com_hibob_anyim_common_protobuf_Body_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_hibob_anyim_common_protobuf_Body_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_hibob_anyim_common_protobuf_Body_descriptor,
        new java.lang.String[] { "FromId", "FromClient", "ToId", "ToClient", "GroupId", "MsgId", "Seq", "Ack", "Content", "TempMsgId", "SessionId", });
    internal_static_com_hibob_anyim_common_protobuf_Extension_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_hibob_anyim_common_protobuf_Extension_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_hibob_anyim_common_protobuf_Extension_descriptor,
        new java.lang.String[] { "ExtensionMap", });
    internal_static_com_hibob_anyim_common_protobuf_Extension_ExtensionMapEntry_descriptor =
      internal_static_com_hibob_anyim_common_protobuf_Extension_descriptor.getNestedTypes().get(0);
    internal_static_com_hibob_anyim_common_protobuf_Extension_ExtensionMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_hibob_anyim_common_protobuf_Extension_ExtensionMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
