
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/anyim?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

# 解决这个错误：org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper';
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 100
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 1200


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  accessToken:
    expire: 1800 #半个小时
    secret: HZHDhdfjdfj
  refreshToken:
    expire: 3600 #1小时
    secret: GHBsfh2sags